- type: entity
  parent: ClothingHeadset
  id: ClothingHeadsetPatologoanatom
  name: гарнитура патологоанатома
  description: Гарнитура что бы рассказать товарищам-медикам о внутреннем мире своих клиентов.
  components:
  - type: ContainerFill
    containers:
      key_slots:
      - EncryptionKeyMedical
      - EncryptionKeyCommon
  - type: Sprite
    sprite: Jobs/Medical/Pathologist/Clothing/headset_patologoanatom.rsi
  - type: Clothing
    sprite: Jobs/Medical/Pathologist/Clothing/headset_patologoanatom.rsi