- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 21600
    - !type:DepartmentTimeRequirement
      department: Juridical
      time: 18000
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-magistrat
  canBeAntag: false
  access:
    - Service
    - Brig
    - Maintenance
    - Command
    - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: IAAGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetJuridical
    neck: ClothingNeckLawyerbadge
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelIAAFilled
  duffelbag: ClothingBackpackDuffelIAAFilled
